export const adminRoutes = [
  {
    path: '',
    title: 'Dashboard',
    iconType: 'material-icons-outlined',
    icon: 'dashboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin', 'Manager'],
    submenu: [
      {
        path: '/admin/dashboard/main',
        title: 'LMS Dashboard',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [],
      },
      {
        path: '/admin/dashboard/analysis',
        title: 'Admin Panel',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [],
      },
    ],
  },
  {
    path: '/users/list',
    title: 'Manage Users',
    iconType: 'material-icons-outlined',
    icon: 'supervised_user_circle',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [],
  },
  {
    path: '/lms/questions/list',
    title: 'Question Bank',
    iconType: 'material-icons-outlined',
    icon: 'question_answer',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin', 'Manager'],
    submenu: [],
  },
  {
    path: '/lms/topics/list',
    title: 'Topic Manager',
    iconType: 'material-icons-outlined',
    icon: 'grain',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [],
  },
  {
    path: '/admin/permissions/list',
    title: 'User Permissions',
    iconType: 'material-icons-outlined',
    icon: 'vpn_lock',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [],
  },
];
