export const lmsRoutes = [
  {
    path: '',
    title: 'LMS Manager',
    iconType: 'material-icons-outlined',
    icon: 'dvr',
    class: 'menu-toggle',
    groupTitle: false,
    badge: 'Beta',
    badgeClass: 'badge bg-blue sidebar-badge float-end',
    role: ['User', 'Admin'],
    submenu: [
      {
        path: '/lms/dashboard',
        title: 'LMS Dashboard',
        iconType: 'material-icons-outlined',
        icon: 'dashboard',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['User', 'Admin'],
        submenu: [],
      },
      {
        path: '/lms/quizzes',
        title: 'My Quizzes',
        iconType: 'material-icons-outlined',
        icon: 'queue_play_next',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['User', 'Admin'],
        submenu: [],
      },
      {
        path: '/lms/questions',
        title: 'My Questions',
        iconType: 'material-icons-outlined',
        icon: 'question_answer',
        class: '',
        badge: '',
        badgeClass: '',
        role: ['User', 'Admin'],
        submenu: [],
      },
      {
        path: '/lms/topics',
        title: 'Topics Manager',
        iconType: 'material-icons-outlined',
        icon: 'grain',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [],
      },
      {
        path: '/lms/certificates',
        title: 'Certificates',
        iconType: 'material-icons-outlined',
        icon: 'card_membership',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [],
      },
    ],
  },
];
