// src/modules/master/routes/lms.routes.ts
export const lmsRoutes = [
  {
    path: '',
    title: 'LMS Manager',
    iconType: 'material-icons-outlined',
    icon: 'dvr',
    class: 'menu-toggle',
    groupTitle: false,
    badge: 'Dev',
    badgeClass: 'badge bg-blue sidebar-badge float-end',
    role: ['Admin'],
    submenu: [
      {
        path: '/lms/dashboard',
        title: 'LMS Dashboard',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/lms/quizzes',
        title: 'Quizzes',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/lms/questions',
        title: 'Questions',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/lms/topics',
        title: 'Manage Topics',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/lms/certificates',
        title: 'Certificates',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
];
