export const lmsRoutes = [
  {
    path: '',
    title: 'LMS Manager',
    iconType: 'material-icons-outlined',
    icon: 'dvr',
    class: 'menu-toggle',
    groupTitle: false,
    badge: 'Beta',
    badgeClass: 'badge bg-blue sidebar-badge float-end',
    role: ['User'],
    submenu: [
      {
        path: '/lms/dashboard',
        title: 'LMS Dashboard',
        iconType: '',
        icon: 'dvr',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['User'],
        submenu: [],
      },
      {
        path: '/lms/quizzes',
        title: 'My Quizzes',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['User'],
        submenu: [],
      },
      {
        path: '/lms/questions',
        title: 'My Questions',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['User'],
        submenu: [],
      },
      {
        path: '/lms/topics',
        title: 'My Topics',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['User'],
        submenu: [],
      },
      {
        path: '/lms/certificates',
        title: 'Certificates',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['User'],
        submenu: [],
      },
    ],
  },
];
