export const welcomeRoutes = [
  {
    path: '/app/welcome',
    title: 'Welcome',
    iconType: 'material-icons-outlined',
    icon: 'insights',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  {
    path: '/app/select-job-role',
    title: 'Browse Tech Roles',
    iconType: 'material-icons-outlined',
    icon: 'school',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  {
    path: '/app/select-subject',
    title: 'Subject Explorer',
    iconType: 'material-icons-outlined',
    icon: 'library_books',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
];
