export enum UserPermissionTitleEnum {
  Subject = 'subject',
  Topic = 'topic',
  Question = 'question',
  SubjectTrack = 'subject-track',
  CertificationTrack = 'certification-track',
  JobRole = 'job-role',
  Badge = 'badge',
}
export enum UserPermissionEnum {
  TopicGet = 'Topic:Get',
  TopicCreate = 'Topic:Create',
  QuestionAuthorCreate = 'QuestionAuthor:Create',
  QuestionAuthorUpdate = 'QuestionAuthor:Update',
  QuestionAuthorDelete = 'QuestionAuthor:Delete',
  LmsManager = 'LmsManager',
  SubjectTrackGet = 'SubjectTrack:Get',
  SubjectTrackCreate = 'SubjectTrack:Create',
  SubjectTrackUpdate = 'SubjectTrack:Update',
  SubjectTrackDelete = 'SubjectTrack:Delete',
  CertificationTrackGet = 'CertificationTrack:Get',
  CertificationTrackCreate = 'CertificationTrack:Create',
  CertificationTrackUpdate = 'CertificationTrack:Update',
  CertificationTrackDelete = 'CertificationTrack:Delete',
  BadgeGrant = 'Badge:Grant',
}
